### ISSUE TITLE
http://www.sueddeutsche.de/ is not compatible with Ruby NET HTTP

### ISSUE THREAD

**Issue by shiroginne** [denkungsart/chat_noir#1]
``` ruby
2.3.1 :005 > require 'open-uri'
 => true 
2.3.1 :006 > open 'http://www.sueddeutsche.de/politik/ukip-nach-dem-brexit-farage-drueckt-sich-vor-der-verantwortung-1.3062729'
Zlib::DataError: incorrect header check
    from /Users/xxxx/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http/response.rb:380:in `inflate'
    from /Users/xxxx/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http/response.rb:380:in `block in inflate_adapter'
    from /Users/xxxx/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/protocol.rb:411:in `call_block'
    from /Users/xxxx/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/protocol.rb:402:in `<<'
    from /Users/xxxx/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/protocol.rb:104:in `read'
    from /Users/xxxx/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http/response.rb:402:in `read'
    from /Users/xxxx/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http/response.rb:291:in `block in read_body_0'
    from /Users/xxxx/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http/response.rb:262:in `inflater'
    from /Users/xxxx/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http/response.rb:281:in `read_body_0'
    from /Users/xxxx/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http/response.rb:202:in `read_body'
    from /Users/xxxx/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/open-uri.rb:334:in `block (2 levels) in open_http'
    from /Users/xxxx/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:1446:in `block in transport_request'
    from /Users/xxxx/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http/response.rb:163:in `reading_body'
    from /Users/xxxx/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:1445:in `transport_request'
    from /Users/xxxx/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:1407:in `request'
    from /Users/xxxx/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/open-uri.rb:325:in `block in open_http'
    from /Users/xxxx/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:853:in `start'
    from /Users/xxxx/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/open-uri.rb:319:in `open_http'
    from /Users/xxxx/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/open-uri.rb:737:in `buffer_open'
    from /Users/xxxx/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/open-uri.rb:212:in `block in open_loop'
    from /Users/xxxx/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/open-uri.rb:210:in `catch'
    from /Users/xxxx/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/open-uri.rb:210:in `open_loop'
    from /Users/xxxx/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/open-uri.rb:151:in `open_uri'
    from /Users/xxxx/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/open-uri.rb:717:in `open'
    from /Users/xxxx/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/open-uri.rb:35:in `open'
    from (irb):6
    from /Users/xxxx/.rvm/rubies/ruby-2.3.1/bin/irb:11:in `<main>'
2.3.1 :007 > 
```

**Comment by fschwahn** [comment]
@shiroginne quickly googling this error brought up that
`open('http://www.sueddeutsche.de/politik/ukip-nach-dem-brexit-farage-drueckt-sich-vor-der-verantwortung-1.3062729', "Accept-Encoding" => "plain").read` works (from http://stackoverflow.com/questions/32873705/open-uri-alternative-getting-a-response-from-a-website).

I guess the gzip response is somehow invalid, and this forces the server to send a plain response. So this should only be a fallback if `Zlib::DataError` occurs.
